CHET-286: update migration helper to drop owner and be more resilient

diff --git a/templates/migration-stack/migration-helper.yml b/templates/migration-stack/migration-helper.yml
--- a/templates/migration-stack/migration-helper.yml
+++ b/templates/migration-stack/migration-helper.yml
@@ -147,15 +147,29 @@ Resources:
                     mkdir -p $DATABASE_DOWNLOAD_DIR
                     DB_DUMP_LOG_FILE="/var/atlassian/dc-migration-assistant/pg_dump-log.txt"
                     SECRET_PASSWORD=`aws secretsmanager  get-secret-value --secret-id ${SecretIdentifier} --region ${AWS::Region} --output text --query "SecretString"`
+                    if [ $? != 0]; then
+                      echo "Error when fetching db password from secret manage"
+                      exit 1
+                    fi
                     aws s3 sync s3://${MigrationBucket}/db.dump/ $DATABASE_DOWNLOAD_DIR --region ${AWS::Region} | tee $DB_DUMP_LOG_FILE
+                    if [ $? != 0]; then
+                      echo "Error when synchronising with the S3 bucket"
+                      exit 1
+                    fi
                     echo "Restoring database from $DATABASE_DOWNLOAD_DIR to ${DBHost}:${DBPort}/$DBName" | tee $DB_DUMP_LOG_FILE
-                    PGPASSWORD=$SECRET_PASSWORD pg_restore -h ${DBHost} -U ${DBUser} -d ${DBName} -p ${DBPort} -F d --verbose $DATABASE_DOWNLOAD_DIR 2>&1 | tee $DB_DUMP_LOG_FILE
-                    PG_RESTORE_EXIT_CODE=$?
-                    ERRORS_EXIST=`grep -qiE 'error|warning' /var/atlassian/dc-migration-assistant/pg_dump-log.txt && echo 'true' || echo 'false'`
-                    RESTORE_COMPLETE=`grep -qiE 'pg_restore: finished main parallel loop' /var/atlassian/dc-migration-assistant/pg_dump-log.txt && echo 'true' || echo 'false'`
-                    echo -e "{\"is_restore_complete\":\""$RESTORE_COMPLETE"\",\"is_error_present\":\""$ERRORS_EXIST"\", "return_code":\""$PG_RESTORE_EXIT_CODE"\"}"
+                    PGPASSWORD=$SECRET_PASSWORD pg_restore --no-owner --no-acl --clean --if-exists -h ${DBHost} -U ${DBUser} -d ${DBName} -p ${DBPort} -F d --verbose $DATABASE_DOWNLOAD_DIR 2>&1 | tee $DB_DUMP_LOG_FILE
+                    ERROR_OUTPUT=$(grep -iE 'error|warning' $DB_DUMP_LOG_FILE)
+
+                    if [ -z "$ERROR_OUTPUT" ]; then
+                            echo "SUCCESS: Database migration was successful"
+                            exit 0
+                    else
+                            echo "Errors:"
+                            echo "${ERROR_OUTPUT}"
+                            echo "ERROR: Database migration wasn't successful"
+                            exit 1
+                    fi
                   - {
-                    SecretIdentifier: !Sub "atl-${AWS::StackName}-app-rds-password",
                     MigrationBucket: !Ref MigrationBucket,
                     DBHost: !Ref RDSEndpoint,
                     DBPort: !Ref RDSPort,
